use crate::schema::Patterns;
use std::path::{Path, PathBuf};

pub fn is_none(value: &str) -> bool {
    let trimmed = value.trim();
    trimmed.is_empty() || trimmed == "none"
}

pub fn display_list(values: &[String]) -> String {
    if values.is_empty() {
        "none".to_string()
    } else {
        values.join(", ")
    }
}

pub fn is_ident_char(character: char) -> bool {
    character.is_ascii_alphanumeric() || character == '-' || character == '@'
}

pub fn replace_identifier(text: &str, from: &str, to: &str) -> String {
    if from.is_empty() || from == to {
        return text.to_string();
    }
    let mut output = String::with_capacity(text.len());
    let mut rest = text;
    while let Some(position) = rest.find(from) {
        let before = &rest[..position];
        let after_index = position + from.len();
        let after = &rest[after_index..];
        let left = before
            .chars()
            .last()
            .map(|character| !is_ident_char(character))
            .unwrap_or(true);
        let right = after
            .chars()
            .next()
            .map(|character| !is_ident_char(character))
            .unwrap_or(true);
        output.push_str(before);
        if left && right {
            output.push_str(to);
        } else {
            output.push_str(from);
        }
        rest = after;
    }
    output.push_str(rest);
    output
}

pub fn apply_replacements(text: &str, mapping: &[(String, String)]) -> String {
    let mut output = text.to_string();
    for (from, to) in mapping {
        output = replace_identifier(&output, from, to);
    }
    output
}

pub fn apply_glossary(title: &str, terms: &[String]) -> String {
    let mut output = title.to_string();
    for term in terms {
        if term.is_empty() {
            continue;
        }
        let mut rebuilt = String::with_capacity(output.len());
        let mut rest = output.as_str();
        let lower_term = term.to_ascii_lowercase();
        while !rest.is_empty() {
            let lower_rest = rest.to_ascii_lowercase();
            let Some(position) = lower_rest.find(&lower_term) else {
                rebuilt.push_str(rest);
                break;
            };
            let (before, matched_and_after) = rest.split_at(position);
            let (_, after) = matched_and_after.split_at(term.len());
            let left = before
                .chars()
                .last()
                .map(|character| !character.is_ascii_alphanumeric())
                .unwrap_or(true);
            let right = after
                .chars()
                .next()
                .map(|character| !character.is_ascii_alphanumeric())
                .unwrap_or(true);
            rebuilt.push_str(before);
            if left && right {
                rebuilt.push_str(term);
            } else {
                rebuilt.push_str(&matched_and_after[..term.len()]);
            }
            rest = after;
        }
        output = rebuilt;
    }
    output
}

pub fn family_of<'a>(patterns: &'a Patterns, identifier: &str) -> Option<&'a str> {
    [
        "DRAFT", "TASK", "D", "R", "B", "C", "T", "I", "Q", "H", "S", "GATE", "DEMO",
    ]
    .into_iter()
    .find(|name| patterns.matches_family(name, identifier))
}

pub fn markdown_files(directory: &Path) -> Vec<PathBuf> {
    let Ok(entries) = std::fs::read_dir(directory) else {
        return Vec::new();
    };
    let mut files: Vec<PathBuf> = entries
        .filter_map(|entry| entry.ok())
        .map(|entry| entry.path())
        .filter(|path| path.extension().is_some_and(|extension| extension == "md"))
        .collect();
    files.sort();
    files
}

pub fn walk_markdown(directory: &Path) -> Vec<PathBuf> {
    let mut files = Vec::new();
    let mut stack = vec![directory.to_path_buf()];
    while let Some(current) = stack.pop() {
        let Ok(entries) = std::fs::read_dir(&current) else {
            continue;
        };
        for entry in entries.filter_map(|entry| entry.ok()) {
            let path = entry.path();
            if path.is_dir() {
                stack.push(path);
            } else if path.extension().is_some_and(|extension| extension == "md") {
                files.push(path);
            }
        }
    }
    files.sort();
    files
}

pub fn ensure_trailing_newline(text: &str) -> String {
    let mut output = text.to_string();
    if !output.ends_with('\n') {
        output.push('\n');
    }
    output
}

pub fn next_number(numbers: impl Iterator<Item = u32>) -> u32 {
    numbers.max().unwrap_or(0) + 1
}

pub fn format_task_id(prefix: &str, number: u32) -> String {
    format!("{prefix}-{number:03}")
}

pub const GENERATED_HEADER: &str = "<!-- GENERATED by roadmap gen from workstreams/, milestones/, registers/, decisions/. Do not edit. -->";

pub const SPIKE_HEADINGS: [&str; 5] = [
    "## Question",
    "## Built",
    "## Measured",
    "## Rules out",
    "## Recommends",
];

pub const IMPERATIVE_VERBS: &[&str] = &[
    "Accept",
    "Add",
    "Adopt",
    "Align",
    "Allow",
    "Apply",
    "Assemble",
    "Assert",
    "Assign",
    "Attach",
    "Audit",
    "Author",
    "Bind",
    "Block",
    "Boot",
    "Bridge",
    "Bring",
    "Build",
    "Bump",
    "Capture",
    "Check",
    "Choose",
    "Claim",
    "Classify",
    "Close",
    "Collect",
    "Compare",
    "Compile",
    "Complete",
    "Compose",
    "Compute",
    "Configure",
    "Connect",
    "Convert",
    "Count",
    "Cover",
    "Create",
    "Decide",
    "Declare",
    "Defer",
    "Define",
    "Delete",
    "Deliver",
    "Deploy",
    "Derive",
    "Describe",
    "Design",
    "Detect",
    "Disable",
    "Dispatch",
    "Document",
    "Drop",
    "Emit",
    "Enable",
    "Encode",
    "Enforce",
    "Enumerate",
    "Establish",
    "Evaluate",
    "Exclude",
    "Execute",
    "Expand",
    "Explain",
    "Explore",
    "Expose",
    "Extend",
    "Extract",
    "Fail",
    "Filter",
    "Find",
    "Finish",
    "Fix",
    "Follow",
    "Fork",
    "Format",
    "Freeze",
    "Generate",
    "Grant",
    "Guard",
    "Handle",
    "Harness",
    "Host",
    "Identify",
    "Implement",
    "Import",
    "Include",
    "Index",
    "Inform",
    "Inherit",
    "Initialise",
    "Initialize",
    "Inspect",
    "Install",
    "Instrument",
    "Integrate",
    "Introduce",
    "Invalidate",
    "Isolate",
    "Issue",
    "Keep",
    "Land",
    "Limit",
    "Link",
    "List",
    "Load",
    "Lock",
    "Log",
    "Maintain",
    "Make",
    "Map",
    "Mark",
    "Match",
    "Measure",
    "Merge",
    "Migrate",
    "Mint",
    "Mirror",
    "Model",
    "Move",
    "Name",
    "Normalise",
    "Normalize",
    "Observe",
    "Open",
    "Own",
    "Package",
    "Parse",
    "Pin",
    "Plan",
    "Port",
    "Prepare",
    "Preserve",
    "Prevent",
    "Print",
    "Produce",
    "Promote",
    "Protect",
    "Prove",
    "Provide",
    "Publish",
    "Raise",
    "Read",
    "Record",
    "Reduce",
    "Refuse",
    "Register",
    "Reject",
    "Release",
    "Remove",
    "Rename",
    "Render",
    "Reopen",
    "Replace",
    "Report",
    "Require",
    "Reserve",
    "Reset",
    "Resolve",
    "Restore",
    "Restrict",
    "Retain",
    "Retire",
    "Return",
    "Reuse",
    "Review",
    "Revise",
    "Revoke",
    "Rewrite",
    "Route",
    "Run",
    "Schedule",
    "Scope",
    "Secure",
    "Select",
    "Send",
    "Separate",
    "Serve",
    "Set",
    "Share",
    "Ship",
    "Show",
    "Sign",
    "Simulate",
    "Specify",
    "Split",
    "Stabilise",
    "Stabilize",
    "Stage",
    "Start",
    "State",
    "Stop",
    "Store",
    "Strip",
    "Submit",
    "Support",
    "Suppress",
    "Switch",
    "Sync",
    "Tag",
    "Take",
    "Target",
    "Teach",
    "Terminate",
    "Test",
    "Trace",
    "Track",
    "Transfer",
    "Transform",
    "Translate",
    "Tune",
    "Turn",
    "Unclaim",
    "Update",
    "Use",
    "Validate",
    "Verify",
    "Version",
    "Wait",
    "Warn",
    "Wire",
    "Wrap",
    "Write",
];

pub fn first_word(title: &str) -> &str {
    title
        .split(|character: char| character.is_whitespace() || character == '/' || character == ':')
        .find(|word| !word.is_empty())
        .unwrap_or(title)
}

pub fn is_imperative_title(title: &str) -> bool {
    let word = first_word(title);
    if IMPERATIVE_VERBS
        .iter()
        .any(|verb| verb.eq_ignore_ascii_case(word))
    {
        return true;
    }
    let lower = word.to_ascii_lowercase();
    let article = matches!(lower.as_str(), "the" | "a" | "an" | "this" | "that");
    let plural_or_gerund =
        (lower.ends_with('s') && !lower.ends_with("ss")) || lower.ends_with("ing");
    let capitalised = word
        .chars()
        .next()
        .is_some_and(|character| character.is_ascii_uppercase());
    capitalised && !article && !plural_or_gerund
}

pub fn strip_generated_text(content: &str) -> String {
    let mut output = String::new();
    let mut inside = false;
    for line in content.lines() {
        if crate::parser::is_marker_begin(line) {
            inside = true;
            continue;
        }
        if crate::parser::is_marker_end(line) {
            inside = false;
            continue;
        }
        if !inside {
            output.push_str(line);
            output.push('\n');
        }
    }
    output
}

pub fn copy_dir(from: &Path, to: &Path) -> std::io::Result<()> {
    std::fs::create_dir_all(to)?;
    for entry in std::fs::read_dir(from)? {
        let entry = entry?;
        let destination = to.join(entry.file_name());
        if entry.path().is_dir() {
            copy_dir(&entry.path(), &destination)?;
        } else {
            std::fs::copy(entry.path(), destination)?;
        }
    }
    Ok(())
}

pub fn matrix_entries(text: &str) -> Vec<String> {
    let pattern =
        regex::Regex::new(r"\b(qemu-[a-z0-9_-]+|hw-h\d{3})\b").expect("matrix entry pattern");
    pattern
        .find_iter(text)
        .map(|found| found.as_str().to_string())
        .collect()
}

#[cfg(test)]
mod tests {
    use super::apply_glossary;

    #[test]
    fn glossary_rewrites_case() {
        let terms = vec!["MemoryObject".to_string(), "Component".to_string()];
        assert_eq!(
            apply_glossary("Implement the memoryobject path", &terms),
            "Implement the MemoryObject path"
        );
    }
}
