mod common;

use roadmap::fmt as formatter;
use roadmap::generate;
use std::collections::BTreeMap;

#[test]
fn fmt_is_idempotent() {
    let repo = common::materialize_valid();
    let first = common::run(&repo.path, &["fmt"]);
    assert!(
        first.status.success(),
        "{}",
        String::from_utf8_lossy(&first.stderr)
    );
    let after_first = snapshot_markdown(&repo.path);
    let second = common::run(&repo.path, &["fmt"]);
    assert!(second.status.success());
    let after_second = snapshot_markdown(&repo.path);
    assert_eq!(after_first, after_second);
    let check = common::run(&repo.path, &["fmt", "--check"]);
    assert!(
        check.status.success(),
        "{}",
        String::from_utf8_lossy(&check.stdout)
    );
}

#[test]
fn gen_is_deterministic() {
    let left = common::materialize_valid();
    let nanos = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .expect("time")
        .as_nanos();
    let right_path =
        std::env::temp_dir().join(format!("roadmap-gen-right-{}-{nanos}", std::process::id()));
    roadmap::util::copy_dir(&left.path, &right_path).expect("copy");
    let right = common::TempRepo { path: right_path };
    assert!(common::run(&left.path, &["gen"]).status.success());
    assert!(common::run(&right.path, &["gen"]).status.success());
    let left_files = generated_snapshot(&left.path);
    let right_files = generated_snapshot(&right.path);
    for key in left_files.keys() {
        assert_eq!(
            left_files.get(key),
            right_files.get(key),
            "generated file {key} differs"
        );
    }
    assert_eq!(
        left_files.keys().collect::<Vec<_>>(),
        right_files.keys().collect::<Vec<_>>()
    );
    let again = common::run(&left.path, &["gen"]);
    assert!(again.status.success());
    assert_eq!(left_files, generated_snapshot(&left.path));
    let check = common::run(&left.path, &["gen", "--check"]);
    assert!(
        check.status.success(),
        "{}",
        String::from_utf8_lossy(&check.stdout)
    );
}

#[test]
fn fmt_applies_glossary_casing() {
    let repo = common::materialize_valid();
    let mut content = common::read(&repo.path, "workstreams/GOV.md");
    content = content.replace(
        "Implement the roadmap validator",
        "Implement the memoryobject path",
    );
    common::write(&repo.path, "workstreams/GOV.md", &content);
    let loaded = common::load(&repo.path, true, None);
    assert!(
        loaded
            .tasks
            .iter()
            .any(|task| task.title.to_ascii_lowercase().contains("memoryobject")),
        "{:?}",
        loaded
            .tasks
            .iter()
            .map(|task| task.title.clone())
            .collect::<Vec<_>>()
    );
    let changes = formatter::format_repo(&loaded).expect("format");
    let formatted = changes
        .into_iter()
        .find(|(path, _, _)| path == "workstreams/GOV.md")
        .map(|(_, body, _)| body)
        .expect("gov");
    assert!(formatted.contains("Implement the MemoryObject path"));
}

#[test]
fn generate_header_is_static() {
    let repo = common::materialize_valid();
    let loaded = common::load(&repo.path, true, None);
    let derived = roadmap::derive::build(&loaded);
    let files = generate::render(&loaded, &derived).expect("render");
    let header = "<!-- GENERATED by roadmap gen from workstreams/, milestones/, registers/, decisions/. Do not edit. -->";
    assert!(files["ROADMAP.md"].starts_with(header));
    assert!(files["STATUS.md"].starts_with(header));
    assert!(files["generated/ready.md"].starts_with(header));
    assert!(!files["ROADMAP.md"].contains("2026-"));
}

fn snapshot_markdown(root: &std::path::Path) -> BTreeMap<String, String> {
    let mut files = BTreeMap::new();
    for relative in [
        "workstreams/GOV.md",
        "milestones/V0.md",
        "decisions/D-0001-process.md",
    ] {
        if let Ok(content) = std::fs::read_to_string(root.join(relative)) {
            files.insert(relative.to_string(), content);
        }
    }
    files
}

fn generated_snapshot(root: &std::path::Path) -> BTreeMap<String, String> {
    let mut files = BTreeMap::new();
    for relative in [
        "ROADMAP.md",
        "STATUS.md",
        "generated/ready.md",
        "generated/blocked.md",
        "generated/critical-path.md",
        "generated/benchmarks.md",
        "generated/graph.dot",
        "generated/index.json",
        "generated/by-milestone/V0.md",
        "generated/by-workstream/GOV.md",
        "workstreams/GOV.md",
        "milestones/V0.md",
        "decisions/README.md",
    ] {
        if let Ok(content) = std::fs::read_to_string(root.join(relative)) {
            files.insert(relative.to_string(), content);
        }
    }
    files
}
